package com.wix.pay.fatzebra.model

case class Purchase(authorization: Option[String] = None,
                    id: Option[String] = None,
                    card_number: Option[String] = None,
                    card_holder: Option[String] = None,
                    card_expiry: Option[String] = None,
                    card_token: Option[String] = None,
                    amount: Option[Int] = None,
                    decimal_amount: Option[Double] = None,
                    successful: Option[Boolean] = None,
                    authorized: Option[Boolean] = None,
                    message: Option[String] = None,
                    reference: Option[String] = None,
                    currency: Option[String] = None,
                    transaction_id: Option[String] = None,
                    settlement_date: Option[String] = None,
                    transaction_date: Option[String] = None,
                    response_code: Option[String] = None,
                    captured: Option[Boolean] = None,
                    captured_amount: Option[Int] = None,
                    rrn: Option[String] = None,
                    cvv_match: Option[String] = None)
